### PR TITLE
WS2-1335: Fix typo in the name space for webspark-module-asu_brand

### PR DESCRIPTION
**Pull request by tbutterf**
I found a typo and fixed it.

### CODE REVIEW

**Comment by tbutterf** [comment]
Looks like the typo is perpetuated from upstream. This needs to be merged after the change in the asu_brand module: https://github.com/ASUWebPlatforms/webspark-module-asu_brand/pull/24

**Comment by mlsamuelson** [comment]
@travisbutterfield Yeah, I noticed that a month or so back - it's on Packagist that way! https://packagist.org/packages/asuwebpplatforms/webspark-module-asu_brand

I must have been under the gun at the time, because I opted to leave it as it was at that time. I should have created a ticket for this. :P It should get one now. Can you create that, so we have a record and and it's tracked in WS2 Jira? Thx.

**Comment by tbutterf** [comment]
@mlsamuelson A ticket has been created, and there's a PR now for webspark-module-asu_brand. Once that gets merged, I can then increment the version in this PR, and it will be good to go.

**Comment by mlsamuelson** [comment]
@tbutterf The other PR is complete. You'll need to make a new release and register the package on packagist.org before this PR can be completed.

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
